### ISSUE TITLE
Measuring page content ahead of time

### ISSUE THREAD

**Issue by mainrs** [typst/pdf-writer#11]
Hey!

I want to use this crate to create PDFs of some text files. The content of the files is rarely larger than 4-8 lines.
Is it somehow possible to automatically shrink the page size once text has been written? Maybe with some way to specify a margin?

Something similar to Latex' `separate` document class :)

Thanks!

**Comment by laurmaedje** [comment]
You can change the page size by modifying the [media box](https://github.com/typst/pdf-writer/blob/55178069d99de58b0a98d9a6330d52aedd297eed/examples/hello.rs#L29). However, this is not automatic, so you'd have to calculate yourself how much space the text needs (which is simple on the Y axis, but more tricky on the X axis). In general, this crate is very low-level, so if you just want to generate PDFs with some lines of text and don't need exact control over things like fonts a more high-level library like [printpdf](https://docs.rs/printpdf/0.5.3/printpdf/) might better fit your use case.

**Comment by mainrs** [comment]
Is it possible to change the media box size afterwards somehow?
Sounds like I need some other crate to do the text measurements.

Out of curiosity, did you open-source the crate you use for typst that does that?

**Comment by laurmaedje** [comment]
You can't change things once they are written, but you can just build the `Content` first, doing your measurements, and write the page object afterwards. 

How to best do the measurements depends on whether you use one of the PDF built-in fonts or a font from a file. If you use one of the builtin ones, you would have to get ahold of its metrics somewhere on the internet. If you have a font file, you can use [ttf-parser](https://github.com/RazrFalcon/ttf-parser) to get the glyph metrics. 

That will do for super basic left-to-right Latin text without kerning. For anything more, you need a proper text shaping engine like [rustybuzz](https://github.com/RazrFalcon/rustybuzz). Typst's text stack is part of our core repository, which is not yet open-source (but will be).
