### ISSUE TITLE
PDF A/1-b

### ISSUE THREAD

**Issue by inzanez** [typst/pdf-writer#12]
Hi

I noticed that you mention PDF/A standard and that current functionality should allow to write documents compliant with that standard. I was just wondering: how would I embed things like ICC color profiles and add a correct OutputIntent?

**Comment by laurmaedje** [comment]
Typed APIs for many PDF/A related things are still missing, including ICC profiles and OutputIntent. For now, you would have to refer to the specification and manually write these structures using the provided primitive writers. I am also curious where you have seen mention of PDF/A in the repository as I could not find any.

**Comment by reknih** [comment]
`OutputIntent` and `ICCBased` color spaces will be supported once #13 is merged
