### ISSUE TITLE
Can provide an example of loading a font from a TTF file?

### ISSUE THREAD

**Issue by czxichen** [typst/pdf-writer#17]

**Comment by czxichen** [comment]
The help was obtained from 'https://github.com/typst'.

**Comment by jonmmease** [comment]
In case anyone else comes across this issue while searching, I created a minimal example of using pdf-writer to write a PDF with embedded TTF font: https://github.com/jonmmease/pdf_writer_font_embed

The logic is entirely lifted from typst

**Comment by laurmaedje** [comment]
I should add that Typst still has a few bugs with font embedding. We fixed some recently (and I see that your minimal example has these fixes already), but there remains a known issue with CJK fonts.

**Comment by jonmmease** [comment]
Thanks for the notes @laurmaedje. It would be great if we could work out a way for the Typst font-embedding logic to be available to consumers of pdf-writer, but for now I'll try to keep an eye out for fixes / improvements you make in typst.

**Comment by laurmaedje** [comment]
I'll think about whether we can somehow extract it!

**Comment by LaurenzV** [comment]
In general, I think it would be really great if we added some more (optional) abstraction APIs on top of `pdf-writer` to make certain things simpler. For example, both `typst` and `svg2pdf` would have a lot to gain from having certain abstractions like the `Remapper` in Typst or the `Deferrer` in `svg2pdf` directly in `pdf-writer`. But it's hard to come up with a nice API for that.

**Comment by laurmaedje** [comment]
pdf-writers API is cool insofar as that it allocates very little, making it fast, but it's a bit painful to write abstractions around it. From time to time, I have thought about writing a 
bit higher-level crate that manages indirect references, allocates IDs, etc while still exposing the full power of raw PDF (in contrast to most other Rust pdf crates).

but maybe we can get quite far with just bundling useful abstractions with pdf-writer. One other such abstraction could be a top-level buffer writer into which you write objects while the main writer is borrowed. And then you flush it into the main writer. (helpful where currently deferred writing is used).

but I'm starting to derail this issue 😅

**Comment by laurmaedje** [comment]
@jonmmease FYI: I [fixed a bug](https://github.com/typst/typst/commit/dad7c88576224f636f9292fd60f0f65dd4b3a043) with CID-keyed font embedding in Typst. Your minimal example will also be affected. It mostly happens with CJK fonts.

**Comment by jonmmease** [comment]
Thanks for the heads up! I didn't port over the CFF logic initially as I wasn't sure how to test that it was working. What is an example of a cff font I could try out?

**Comment by jonmmease** [comment]
Out of curiosity, do the PDFs you generate with Source Han Sans CN display properly in pdfium in Chrome? Following the typst logic I see things working in Acrobat, but the non-latin characters are not displayed Chrome.
