### ISSUE TITLE
How to add an image to pdf ?

### ISSUE THREAD

**Issue by akhilmhdh** [typst/pdf-writer#5]
Hey there,

First of all thank you for creating this crate. I was using this with svg2pdf to generate images for a personal project and its been great.

But due to sv2pdf rasterizing the file size seems to be soo big. So planning to change to png image by [image](https://crates.io/crates/image) crate . Can you please share some insights on how to add a png to pdf. 

I saw there is image x_objects. But can't seem to understand on how to position the elements and on how to also use it properly. Has been reading the source code for quite sometime.

```rs
let id = Ref::new(5);

let sample  = image::from("/file.png");
 let image = writer.image_xobject(id, sample);
 image.finish();
```

By reading some of the dependent codebase came to this. But still unsure like how to place an image at a particular location in a page.

Would be great if you could add an example.

Thank you

**Comment by akhilmhdh** [comment]
Also sorry, this is not an issue but rather a doubt, Didn't find the discussion tab as I think its disabled.

**Comment by akhilmhdh** [comment]
Hey @reknih .

Yup. Agreed. But weird part for me here is, I did apply compression using [flate2](https://crates.io/crates/flate2) crate

```rs
let final_svg =format!(
                "<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" stroke=\"none\" width=\"595\" height=\"842\">\n {} </svg>\n",svg);

                let tree = Tree::from_str(&final_svg, &usvg::Options::default().to_ref()).unwrap();
                svg2pdf::convert_tree_into(&tree, svg2pdf::Options::default(), &mut writer, svg_id);

                let mut content = Content::new();
                content
                    .transform([page_w, 0.0, 0.0, page_h, 00.0, 0.0])
                    .x_object(svg_name);

                let data = content.finish();
                println!("Raw: {:?}", data.len());

                let mut encoder = ZlibEncoder::new(Vec::new(), Compression::best());
                encoder.write_all(&data.as_slice()).unwrap();
                let compressed = encoder.finish().unwrap();
                println!("Compressed : {:?}", compressed.len());

                writer
                    .stream(content_id, &compressed)
                    .filter(Filter::FlateDecode);
```
Just a snippet of the compression part. This is the example of sv2pdf with pdfwriter. Just added compression.

Btw thank you svg2pdf also. Really helpful, given its speed, quite fast than other kinda of encoding

**Comment by akhilmhdh** [comment]
Got it. 

But i did another thing though. I used [lopdf](https://github.com/J-F-Liu/lopdf) crate and after writer.finish, i loaded it into lopdf and then applied document.compress method. 

It reduced 1.5gb file to 200mb size but took  quite some time. The time is taken because writer.finish ended up as 1.5gb.

Was thinking can i do before that? Like may be iterate though the pdf and encode it with a compression. But didn't find a method like that. 

Same effect was when i zipped the pdf. Reduced drastically but wont solve the actual pdf size though.

I think i may have caused some confusion. 😅

**Comment by akhilmhdh** [comment]
@reknih  @laurmaedje 

Just another question, is there any relationship between page_id and content id other than being unique i32. 

I am trying to create dynamically. But unique caused writer.finish in stuck. So ended up giving really big values for content id then  writer started writing smooth.

So i was thinking there must be a relation between page_id and content_id in a pdf. I read the PDF spec but found out that only criteria is uniqueness. Is there anything I am missing

**Comment by laurmaedje** [comment]
There is no relationship between page ids and content ids. I think your problem is that you have duplicate ids in your document. svg2pdf often needs multiple indirect objects to recreate the SVG. That's way `convert_tree_into` takes _and_ returns a `Ref`. You say which id it should start using, it uses as many ids as necessary and returns the next free id back for you. Multiplying by 5000 fixes the issue because svg2pdf doesn't need 5000 objects in this case.

pdf-writer got stuck because the code that creates the xref table failed to handle duplicate ids. I changed it so that it will now panic with a descriptive message and the duplicate id instead.
